# Generated by Django 2.2.1 on 2019-07-25 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('given_name', models.CharField(max_length=60)),
                ('middle_initial', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccreditingBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrediting_body', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'accreditingBodies',
            },
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=60)),
                ('program_name', models.CharField(max_length=60)),
                ('program_est', models.CharField(max_length=60)),
                ('program_grads', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentOutline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=120)),
                ('accrediting_body_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.AccreditingBody')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=60)),
                ('file_type', models.CharField(max_length=30)),
                ('file_document', models.FileField(max_length=250, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrediting_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.AccreditingBody')),
                ('teams_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.Team')),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrevAccreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_agency', models.CharField(max_length=60)),
                ('accreditation_result', models.CharField(max_length=60)),
                ('accreditation_year', models.CharField(max_length=60)),
                ('degree_program_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.DegreeProgram')),
            ],
        ),
        migrations.CreateModel(
            name='OngoingAccreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrediting_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.AccreditingBody')),
                ('degree_program_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.DegreeProgram')),
                ('document_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.DocumentOutline')),
                ('teams_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentOutlineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=60)),
                ('item_type', models.CharField(max_length=60)),
                ('document_outline_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.DocumentOutline')),
                ('parent_document_outline_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.DocumentOutlineItem')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedAccreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_result', models.CharField(max_length=60)),
                ('completed_year', models.CharField(max_length=60)),
                ('accrediting_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.AccreditingBody')),
                ('degree_program_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.DegreeProgram')),
                ('document_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.DocumentOutline')),
                ('teams_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrediting_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.AccreditingBody')),
                ('document_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.DocumentOutline')),
                ('document_outline_item_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.DocumentOutlineItem')),
                ('teams_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ams.Team')),
            ],
        ),
    ]
