# Generated by Django 2.2.1 on 2019-07-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='UserTeams',
            new_name='UserTeam',
        ),
        migrations.AlterModelOptions(
            name='accreditingbody',
            options={'verbose_name_plural': 'accrediting_Bodies'},
        ),
        migrations.AlterModelOptions(
            name='chapterteam',
            options={'verbose_name_plural': 'team_Chapters'},
        ),
        migrations.AlterModelOptions(
            name='completedaccreditation',
            options={'verbose_name_plural': 'completed_Accreditations'},
        ),
        migrations.AlterModelOptions(
            name='degreeprogram',
            options={'verbose_name_plural': 'degree_Programs'},
        ),
        migrations.AlterModelOptions(
            name='documentoutline',
            options={'verbose_name_plural': 'document_Outlines'},
        ),
        migrations.AlterModelOptions(
            name='documentoutlineitem',
            options={'verbose_name_plural': 'document_Outline_Items'},
        ),
        migrations.AlterModelOptions(
            name='ongoingaccreditation',
            options={'verbose_name_plural': 'ongoing_Accreditations'},
        ),
        migrations.AlterModelOptions(
            name='prevaccreditation',
            options={'verbose_name_plural': 'previous_Program_Accreditations'},
        ),
        migrations.AlterModelOptions(
            name='userteam',
            options={'verbose_name_plural': 'team_Members'},
        ),
        migrations.RenameField(
            model_name='chapterteam',
            old_name='teams_id',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='completedaccreditation',
            old_name='teams_id',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='ongoingaccreditation',
            old_name='teams_id',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='userteam',
            old_name='teams_id',
            new_name='team_id',
        ),
    ]
